<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE Entities [
  <!ELEMENT Entities ANY>
  
  <!ELEMENT Entity ANY>
  <!ATTLIST Entity Id ID #REQUIRED>
  <!ATTLIST Entity Inherits IDREF #IMPLIED>

  <!ELEMENT Component ANY>
  <!ATTLIST Component Type CDATA #REQUIRED>

  <!ELEMENT Property ANY>
  <!ATTLIST Property PropertyName CDATA #REQUIRED>
  <!ATTLIST Property PropertyValue CDATA #REQUIRED>
]>

<Entities>
  
  <Entity Id="PhysicalObject">
    <Component Type="Visual">
      <Property PropertyName="DisplayName" PropertyValue="[PhysicalObject]" />
      <Property PropertyName="Sprite" PropertyValue="error" />
      <Property PropertyName="Description" PropertyValue="[represents a physical object]" />
    </Component>
    <Component Type="PhysicalAttributes">
      <Property PropertyName="Solid" PropertyValue="True" />
      <Property PropertyName="OccludesVison" PropertyValue ="True" />
    </Component>
    <Component Type="Health" />
  </Entity>

  <Entity Id="Wall" Inherits="PhysicalObject">
    <Component Type="Visual">
      <Property PropertyName="DisplayName" PropertyValue="[Wall]" />
      <Property PropertyName="Sprite" PropertyValue="dots2x2" />
      <Property PropertyName="Description" PropertyValue="[a wall]" />
    </Component>

    <Component Type="Health">
      <Property PropertyName="HealthMax" PropertyValue="100" />
      <Property PropertyName="HealthCurrent" PropertyValue="100" />
      <Property PropertyName="Defense" PropertyValue="1" />
    </Component>
  </Entity>

  <Entity Id="LimestoneWall" Inherits="Wall">
    <Component Type="Visual">
      <Property PropertyName="DisplayName" PropertyValue="oolitic limestone wall" />
      <Property PropertyName="Description" PropertyValue="a sedimentary material. the oolites, which are small spherical grains of rock, appear to move and shift like a school of fish" />
      <Property PropertyName="ColorPrimary" PropertyValue="1,1,0.89" />
      <Property PropertyName="ColorSecondary" PropertyValue="0.76,0.76,0.63" />
      <Property PropertyName="ColorTertiary" PropertyValue="0,0,0" />
      <Property PropertyName="Sprite" PropertyValue="dots3x3" />
    </Component>
  </Entity>
  
  <Entity Id="LimestoneWallAlt" Inherits="Wall">
    <Component Type="Visual">
      <Property PropertyName="DisplayName" PropertyValue="sun-bleached oolitic limestone wall" />
      <Property PropertyName="Description" PropertyValue="a sedimentary material. the oolites, which are small spherical grains of rock, appear to move and shift like a school of fish. It has weathered many years of direct exposure to the sun" />
      <Property PropertyName="ColorPrimary" PropertyValue="0.99,0.99,0.92" />
      <Property PropertyName="ColorSecondary" PropertyValue="0.76,0.76,0.69" />
      <Property PropertyName="ColorTertiary" PropertyValue="0,0,0" />
      <Property PropertyName="Sprite" PropertyValue="dots2x2" />
    </Component>
  </Entity>
  
</Entities>